---
title: "Lab 1: Intro to R"
author: "Jian Zheng"
date: "`r Sys.Date()`"
output: openintro::lab_report
---

Code generated by ChatGPT

# Chisq test for two variables
## raw data
```{r}
Variable1 <- c("A", "B", "B", "B", "A", "A", "B", "A", "A", "B","A", "B", "B", "B", "A", "B", "B", "A", "A", "B","A", "B", "B", "B", "A", "A", "B", "A", "A", "B","A", "B", "B", "B", "A", "B", "B", "A", "A", "B")
Variable2 <- c("X", "Y", "X", "X", "X", "Y", "Y", "Y", "Y", "Y","X", "Y", "X", "X", "X", "Y", "Y", "Y", "Y", "Y","X", "Y", "X", "X", "X", "Y", "Y", "Y", "Y", "Y","X", "Y", "X", "X", "X", "Y", "Y", "Y", "Y", "Y")

contingency_table <- table(Variable1, Variable2)
chisq.test(contingency_table)
```

## frequency

```{r}
chisq.test(rbind(c(8,10),c(8,14)))
```

# Chisq test for one variable
## raw data

### with the p value
```{r}
Variable2 <- c("X", "Y", "X", "X", "X", "Y", "Y", "Y", "Y", "Y","X", "Y", "X", "X", "X", "Y", "Y", "Y", "Y", "Y","X", "Y", "X", "X", "X", "Y", "Y", "Y", "Y", "Y","X", "Y", "X", "X", "X", "Y", "Y", "Y", "Y", "Y")

chisq.test(table(Variable2), p = c(0.5,0.5))
```

### without the p value
```{r}
chisq.test(table(Variable2))
```
## frequency/count data
### with the p value
```{r}
observed_frequencies <- c(16, 24)
expected_probabilities <- c(1/2, 1/2)

chisq.test(observed_frequencies, p = expected_probabilities)
```
### without the p value
```{r}
chisq.test(observed_frequencies)
```

## practice with a real dataset: mpg, focusing on year and drv

```{r}
chisq.test(table(mpg$drv))
chisq.test(table(mpg$year,mpg$drv))
```

