---
title: "Lab 1: Intro to R"
author: "Jian Zheng"
date: "`r Sys.Date()`"
output: openintro::lab_report
---

Code generated with ChatGPT

# Chisq test for two variables
## raw data
```{r}
Variable1 <- c("A", "B", "B", "B", "A", "A", "B", "A", "A", "B","A", "B", "B", "B", "A", "B", "B", "A", "A", "B","A", "B", "B", "B", "A", "A", "B", "A", "A", "B","A", "B", "B", "B", "A", "B", "B", "A", "A", "B")
Variable2 <- c("X", "Y", "X", "X", "X", "Y", "Y", "Y", "Y", "Y","X", "Y", "X", "X", "X", "Y", "Y", "Y", "Y", "Y","X", "Y", "X", "X", "X", "Y", "Y", "Y", "Y", "Y","X", "Y", "X", "X", "X", "Y", "Y", "Y", "Y", "Y")


```

## frequency

```{r}
table1 <- rbind(c(80,10),c(8,64))

```

# Chisq test for one variable
## raw data

### with the p value
```{r}
Variable2 <- c("X", "Y", "X", "X", "X", "Y", "Y", "Y", "Y", "Y","X", "Y", "X", "X", "X", "Y", "Y", "Y", "Y", "Y","X", "Y", "Y", "Y", "Y", "Y", "Y", "Y", "Y", "Y","Y", "Y", "X", "X", "X", "Y", "Y", "Y", "Y", "Y", "Z", "Z", "Z", "Z", "Z", "Z", "Z")

```

### without the p value
```{r}

```
## frequency/count data
### with the p value
```{r}
observed_frequencies <- c(16,24)
expected_probabilities <- c(1/2, 1/2)

```
### without the p value
```{r}
chisq.test(observed_frequencies, p = expected_probabilities)
```

## practice with a real dataset: mpg, focusing on year and drv

```{r}
library(tidyverse)
?mpg
glimpse(mpg)
```

