---
title: "INST Lab 4"
author: "Jian Zheng"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries

```{r}
library(tidyverse)
library(ggplot2)
```

# Explore data mpg

```{r}
mpg
?mpg
summary(mpg)
glimpse(mpg)
dim(mpg)
head(mpg)
```

# Contingency Table

```{r}
table(mpg$cyl, mpg$drv)
```
```{r}
table(mpg$drv)
chisq.test(table(mpg$drv))
```

# Bar plot

Basic bar plot

```{r}
ggplot(data = mpg, aes(x = cyl)) +
  geom_bar()
```

Stacked

```{r}
ggplot(data = mpg, aes(x = cyl, fill = drv)) +
  geom_bar()
```

Dodge

```{r}
ggplot(data = mpg, aes(x = cyl, fill = drv)) +
  geom_bar(position = 'dodge')
```

Fill

```{r}
ggplot(data = mpg, aes(x = cyl, fill = drv)) +
  geom_bar(position = 'fill')
```

# As factor

Basic bar chart

```{r}
ggplot(data = mpg, aes(x = as.factor(cyl))) +
  geom_bar()
```

Stacked

```{r}
ggplot(data = mpg, aes(x = as.factor(cyl), fill = drv)) +
  geom_bar()
```

Dodge

```{r}
ggplot(data = mpg, aes(x = as.factor(cyl), fill = drv)) +
  geom_bar(position = 'dodge')
```

Dodge, same width

```{r}
ggplot(data = mpg, aes(x = as.factor(cyl), fill = drv)) +
  geom_bar(position = position_dodge(preserve = 'single'))
```

Fill

```{r}
ggplot(data = mpg, aes(x = as.factor(cyl), fill = drv)) +
  geom_bar(position = 'fill')
```

# Mosaic

Install & load library

```{r}
#install.packages('ggmosaic')
library(ggmosaic)

```

One variable

```{r}
ggplot(data = mpg) +
  geom_mosaic(aes(x = product(cyl)))
```

two variable

```{r}
ggplot(data = mpg) +
  geom_mosaic(aes(x = product(cyl), fill=drv))
```
