---
title: "week5_lab_notes"
author: "YZ & JZ"
date: '2023-02-17'
output: html_document
---
source 1: http://htmlpreview.github.io/?https://github.com/andrewpbray/oiLabs-base-R/blob/master/sampling_distributions/sampling_distributions.html

source 2: http://htmlpreview.github.io/?https://github.com/andrewpbray/oiLabs-base-R/blob/master/confidence_intervals/confidence_intervals.html

```{r setup}
download.file("http://www.openintro.org/stat/data/ames.RData", destfile = "ames.RData")
load("ames.RData")

#We see that there are quite a few variables in the data set, enough to do a very in-depth analysis. For this lab, we’ll restrict our attention to just two of the variables: the above ground living area of the house in square feet (Gr.Liv.Area) and the sale price (SalePrice). To save some effort throughout the lab, create two variables with short names that represent these two variables.

area <- ames$Gr.Liv.Area
price <- ames$SalePrice

#Let’s look at the distribution of area in our population of home sales by calculating a few summary statistics and making a histogram.
summary(area)
hist(area)
```

```{r explore the sample}
#collects a random sample of size 50 from the population

samp1 <- sample(area, 50)
#This command collects a simple random sample of size 50 from the vector area, which is assigned to samp1.

mean(samp1)
#Depending on which 50 homes you selected, your estimate could be a bit above or a bit below the true population mean of 1499.69 square feet. In general, though, the sample mean turns out to be a pretty good estimate of the average living area, and we were able to get it by sampling less than 3% of the population.


#Not surprisingly, every time we take another random sample, we get a different sample mean. It’s useful to get a sense of just how much variability we should expect when estimating the population mean this way. The distribution of sample means, called the sampling distribution, can help us understand this variability. In this lab, because we have access to the population, we can build up the sampling distribution for the sample mean by repeating the above steps many times. Here we will generate 5000 samples and compute the sample mean of each.
```

```{r}
#rep replicates the values in x. It is a generic function, and the (internal) default method is described here.
sample_means50 <- rep(NA, 5000)


for(i in 1:5000){
   samp <- sample(area, 50)
   sample_means50[i] <- mean(samp)
   }

hist(sample_means50)

hist(sample_means50, breaks = 25)


#if we do it by hand, not using for loop - a lot of work 
sample_means50 <- rep(NA, 5000)

samp <- sample(area, 50)
sample_means50[1] <- mean(samp)

samp <- sample(area, 50)
sample_means50[2] <- mean(samp)

samp <- sample(area, 50)
sample_means50[3] <- mean(samp)

samp <- sample(area, 50)
sample_means50[4] <- mean(samp)

#...
```

```{r}

#what if we increase the sample size?  We will see larger sample size has a smaller spread

#different sample size
sample_means10 <- rep(NA, 5000)
sample_means100 <- rep(NA, 5000)
sample_means1000 <- rep(NA, 5000)

for(i in 1:5000){
  samp <- sample(area, 10)
  sample_means10[i] <- mean(samp)
  samp <- sample(area, 100)
  sample_means100[i] <- mean(samp)
  samp <- sample(area, 1000)
  sample_means1000[i] <- mean(samp)
}

#The first command specifies that you’d like to divide the plotting area into 3 rows and 1 column of plots (to return to the default setting of plotting one at a time, use par(mfrow = c(1, 1)))
par(mfrow = c(3, 1))

#The breaks argument specifies the number of bins used in constructing the histogram. The xlim argument specifies the range of the x-axis of the histogram, and by setting it equal to xlimits for each histogram, we ensure that all three histograms will be plotted with the same limits on the x-axis.
xlimits <- range(sample_means10)

hist(sample_means10, breaks = 20, xlim = xlimits)
hist(sample_means100, breaks = 20, xlim = xlimits)
hist(sample_means1000, breaks = 20, xlim = xlimits)
```

```{r confidence intervals}
population <- ames$Gr.Liv.Area
samp <- sample(population, 60)

#Return for a moment to the question that first motivated this lab: based on this sample, what can we infer about the population? Based only on this single sample, the best estimate of the average living area of houses sold in Ames would be the sample mean, usually denoted as x¯
# (here we’re calling it sample_mean). That serves as a good point estimate but it would be useful to also communicate how uncertain we are of that estimate. This can be captured by using a confidence interval.


sample_mean <- mean(sample_means10)
se <- sd(sample_means10) / sqrt(10)
lower <- sample_mean - 1.96 * se
upper <- sample_mean + 1.96 * se
c(lower, upper)
```

```{r}
sample_mean <- mean(sample_means100)
se <- sd(sample_means100) / sqrt(100)
lower <- sample_mean - 1.96 * se
upper <- sample_mean + 1.96 * se
c(lower, upper)
```

```{r}
sample_mean <- mean(sample_means1000)
se <- sd(sample_means1000) / sqrt(1000)
lower <- sample_mean - 1.96 * se
upper <- sample_mean + 1.96 * se
c(lower, upper)
```


